services:
  - type: web
    name: list-pokup
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
    autoDeploy: true
