# Generated by Django 4.2 on 2026-03-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(help_text='Uzunligi (m)')),
                ('width', models.FloatField(help_text='Eni (m)')),
                ('thickness', models.FloatField(help_text='Qalinligi (m)')),
                ('density', models.FloatField(help_text='Zichligi (kg/m³)')),
                ('price_per_kg', models.DecimalField(decimal_places=2, help_text="Kg uchun narx (so'm)", max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.sheet')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.store')),
            ],
        ),
    ]
