# Generated by Django 4.2 on 2026-03-24 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_delete_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Xarid', 'verbose_name_plural': 'Xaridlar'},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Magazin', 'verbose_name_plural': 'Magazinlar'},
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='sheet',
        ),
        migrations.AddField(
            model_name='purchase',
            name='density',
            field=models.FloatField(default=0, help_text='Zichligi (kg/m³)', verbose_name='Zichlik'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='length',
            field=models.FloatField(default=0, help_text='Uzunligi (m)', verbose_name='Uzunlik'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Kg uchun narx (so'm)", max_digits=10, verbose_name='Kg uchun narx'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='thickness',
            field=models.FloatField(default=0, help_text='Qalinligi (m)', verbose_name='Qalinlik'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='width',
            field=models.FloatField(default=0, help_text='Eni (m)', verbose_name='En'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Soni'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.store', verbose_name='Magazin'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Magazin nomi'),
        ),
        migrations.DeleteModel(
            name='Sheet',
        ),
    ]
