# Generated by Django 4.2 on 2026-03-25 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0004_purchase_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Yaratish'), ('update', 'Yangilash'), ('delete', "O'chirish")], max_length=10, verbose_name='Amal')),
                ('model_type', models.CharField(choices=[('store', 'Magazin'), ('purchase', 'Xarid'), ('user', 'Foydalanuvchi')], max_length=10, verbose_name='Model turi')),
                ('object_id', models.PositiveIntegerField(verbose_name='Obekt ID')),
                ('object_repr', models.CharField(max_length=200, verbose_name='Obekt nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bajaruvchi')),
            ],
            options={
                'verbose_name': 'Tarix',
                'verbose_name_plural': 'Tarix',
                'ordering': ['-timestamp'],
            },
        ),
    ]
