# Generated by Django 4.2 on 2026-03-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name="Brauzer ma'lumoti"),
        ),
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('create', 'Yaratish'), ('update', 'Yangilash'), ('delete', "O'chirish"), ('login', 'Tizimga kirish'), ('logout', 'Tizimdan chiqish')], max_length=10, verbose_name='Amal'),
        ),
        migrations.AlterField(
            model_name='history',
            name='model_type',
            field=models.CharField(choices=[('store', 'Magazin'), ('purchase', 'Xarid'), ('user', 'Foydalanuvchi'), ('auth', 'Avtorizatsiya')], max_length=10, verbose_name='Model turi'),
        ),
        migrations.AlterField(
            model_name='history',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Obekt ID'),
        ),
    ]
